---
apiVersion: v1
kind: Pod
metadata: 
  name: mytomcatpod
  labels:
    author: mantu
    app: nginx
spec:
  containers:
  - name: c1
    image: nginx
    ports:
    - containerPort: 8080
      hostPort: 30000
...
